
plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev.legacyforge' version '2.0.95'
}

repositories {
    maven { url 'https://cursemaven.com'}
    maven { url "https://maven.blamejared.com/" }
    maven { url "https://modmaven.dev" }
    maven { url = "https://maven.createmod.net" } // Create, Ponder, Flywheel
    maven { url = "https://maven.tterrag.com" } // Registrate
    maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/" } // ForgeConfigAPIPort
    maven { url = "https://api.modrinth.com/maven" }
    mavenCentral()
}

group = 'net.abraxator.moresnifferflowers'
base {
    archivesName.set("MoreSnifferFlowers-${minecraft_version}-Forge")
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"


    legacyForge {
        version = project.minecraft_version+'-'+forge_version

        parchment {
            mappingsVersion = project.parchment_mappings_version
            minecraftVersion = project.minecraft_version
        }

        runs {
            configureEach {
                gameDirectory = layout.projectDir.dir("runs/$name")
                systemProperty 'forge.logging.console.level', 'debug'
                systemProperty 'forge.logging.markers', 'REGISTRIES'

            }
            client {
                client()
            }
            clientAuth {
                client()
                devLogin = true
                gameDirectory = layout.projectDir.dir("runs/client")
            }
            data {
                data()
                programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
            }
            server {
                server()
                programArgument('--nogui')
            }
        }
        mods {
            more_sniffer_flowers {
                sourceSet(sourceSets.main)
            }
        }
    }

// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    //jei
    modCompileOnlyApi("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")
    modCompileOnlyApi("mezz.jei:jei-${minecraft_version}-forge-api:${jei_version}")

    // Sometimes JEI disappears for some reason
    // modRuntimeOnly("mezz.jei:jei-${minecraft_version}-forge:${jei_version}")
    modRuntimeOnly("curse.maven:jei-238222:6075247")


    // MODS FOR COMPATIBILITY TESTS

    // shaders

    // compileOnly("org.embeddedt:embeddium-1.20.1:0.3.32-beta.64+mc1.20.1") // This shit does NOT work!
    // modRuntimeOnly("org.embeddedt:embeddium-1.20.1:0.3.32-beta.64+mc1.20.1")
    // modRuntimeOnly("curse.maven:oculus-581495:6020952")


    // create

    // modCompileOnly("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
    // modImplementation("net.createmod.ponder:Ponder-Forge-${minecraft_version}:${ponder_version}")
    // modCompileOnly("dev.engine-room.flywheel:flywheel-forge-api-${minecraft_version}:${flywheel_version}")
    // modRuntimeOnly("dev.engine-room.flywheel:flywheel-forge-${minecraft_version}:${flywheel_version}")
    // modImplementation("com.tterrag.registrate:Registrate:${registrate_version}")

   // modRuntimeOnly("curse.maven:farmers-delight-398521:6917255");

    //mixin
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    implementation(jarJar(group: "io.github.llamalad7", name:"mixinextras-forge", version: "[0.5.0,)"))
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.0"))

    implementation 'org.jetbrains:annotations:26.0.1'

    //quark
    compileOnly("curse.maven:quark-243121:6427817")
    compileOnly("curse.maven:zeta-968868:6432578")

    //right click harvest
    compileOnly("curse.maven:rightclickharvest-452834:6326903")
}

mixin {
    add sourceSets.main, 'more_sniffer_flowers.mixins.refmap.json'
    config 'more_sniffer_flowers.mixins.json'
}

final manifestAttributes = [
        'Specification-Title'   : 'MoreSnifferFlowers',
        'Specification-Vendor'  : 'Nikdo53',
        'Specification-Version' : '1',
        'Implementation-Title'  : project.name,
        'Implementation-Version': project.version,
        'Implementation-Vendor' : 'Nikdo53',
        "MixinConfigs"          : "more_sniffer_flowers.mixins.json",
        'jei_version'           : project.jei_version_range,
]

jar {
    manifest.attributes(manifestAttributes)
    finalizedBy('reobfJar')
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}